### ISSUE TITLE
"issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by rinahorigami** [rinahorigami/Ramen_sounds#19]
### 実装予定の機能
- [ ] 会員登録
- [ ] ログイン
- [ ] 動画投稿
- [ ] 投稿動画編集・削除
- [ ] 投稿動画一覧
- [ ] 検索機能
   - [ ] 店舗名
   - [ ] 場所
   - [ ] タグ
- [ ] いいね
- [ ] タグ
- [ ] コメント
- [ ] パスワードリセット

### 必要なページ
- [ ] トップページ
- [ ] 会員登録
- [ ] ログイン
- [ ] パスワードリセット
- [ ] 動画投稿
- [ ] 投稿動画一覧
- [ ] 検索ページ
- [ ] 店舗名検索結果
- [ ] 場所検索結果
- [ ] タグ検索結果
- [ ] マップ(店舗位置情報)
- [ ] 店舗詳細
- [ ] マイページ
  - [ ] 投稿動画一覧
  - [ ] 投稿動画詳細
  - [ ] 投稿動画編集・削除
  - [ ] いいね動画一覧
  - [ ] プロフィール編集
- [ ] コメント投稿・一覧ページ

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
GitHubProjectsが確認できませんでしたので、こちらご確認いただいてもよろしいですか？
(作成してあるが見れない場合、private設定にしてあることが多いです。)
よろしくお願いします。

[![Image from Gyazo](https://t.gyazo.com/teams/startup-technology/865ede98534daeabcbf31a6a7badefe8.png)](https://startup-technology.gyazo.com/865ede98534daeabcbf31a6a7badefe8)

**Comment by Tsuchiya2** [comment]
<img width="1018" alt="image" src="https://github.com/user-attachments/assets/04957280-19d4-4ffe-acfa-6da09e242c6c">

私の方でもProjectsにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただき、看板・issue・ストーリーポイントが確認できる状態でご提出をお願いいたします。

また、tmtkzk0823講師のコメントに対して何も記載されていませんが、これはコメントをするまでもないという意志の表れでしょうか。もしそうでしたら開発現場では共同でプロジェクトを進めていくので、今のうちから適切なテキストコミュニケーションを取れるように意識していきましょう。

**Comment by rinahorigami** [comment]
大変申し訳ございません。
コメントのやり方を理解しておりませんでした。
また、projectをリンクさせていなかったため、リンクいたしました。
project確認できますでしょうか？
度々お手数おかけし大変申し訳ございませんが、レビューよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
確認できました。
概ね良いかと思います。LGTMです。

---

MVP後でも良いと感じたカード
- パスワードリセット
- マイページ

**Comment by rinahorigami** [comment]
承知いたしました。
ありがとうございます。
