### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by rinahorigami** [rinahorigami/Ramen_sounds#47]
## 各種情報
Ramen sounds
https://ramen-sounds-app-95c20e114bcf.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [ ] ユーザー登録
- [ ] ログイン
- [ ] 動画投稿
- [ ] 動画編集・削除
- [ ] 投稿一覧
- [ ] 店舗詳細
- [ ] いいね
- [ ] マイページ
- [ ] 検索
   - 店舗名
   - 場所
   - タグ

## READMEレビュー時から変更した機能
面談で相談し、MVPリリース時の機能を絞りました。
下記機能は本リリース時に作成予定です。
- [ ] いいね
- [ ] タグ付け
- [ ] マイページ
- [ ] 検索
   -   場所
   - タグ

## 本リリース時
- [ ] 位置情報（Google Maps APIを利用）
- [ ] コメント
- [ ] パスワードリセット

現時点では位置情報機能を追加していないため、店舗検索では東京の一部の範囲の検索しかできない状態です。
本リリース時には位置情報機能を追加して、位置情報を元に近くの店舗を検索できるように実装予定です。
よろしくお願いいたします。

**Comment by TakenakaEri** [comment]
MVPリリースの内容が実装できているか確認させていただきました！LGTMです！

個人的には、投稿を行う際に、ASMRの動画を上げる方はラーメン店舗を選ばない方もいるかもしれないので、店舗選択は必須ではなくてもいいのかと思いました。

他の人にも使ってもらった感想をもらって、本リリースまでブラッシュアップしてください！

**Comment by rinahorigami** [comment]
アドバイス頂きありがとうございます！
本リリースに向けて、他の人にも意見を聞いて進めていきたいと思います！
